### PR TITLE
Omeka import

### LINKED ISSUE #6: GitHub Action for GHpages deployment
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

TBD

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

See <https://github.com/CollectionBuilder/collectionbuilder-csv/issues/41> for further reference

### LINKED ISSUE #8: Omeka S integration
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

TBD (should include Docs as well!)

- https://omeka.unibe.ch/s/stadtgeschichtebasel
- https://omeka.unibe.ch/api/sites/29
- https://omeka.unibe.ch/api/resource_templates/33
- https://omeka.unibe.ch/api/item_sets/XXX
- https://omeka.org/s/docs/developer/api/rest_api/
- https://chat.openai.com/share/71c41b7d-c264-470f-bdad-e95a28595fb1

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

See also <https://github.com/CollectionBuilder/collectionbuilder-csv/issues/6> and <https://github.com/CollectionBuilder/collectionbuilder-csv/issues/4>, especially <https://github.com/CollectionBuilder/collectionbuilder-csv/issues/6#issuecomment-1864886181>

### PR DESCRIPTION
**Pull request by maehr**
# Pull request

## Proposed changes

- Fix #8 
- Fix #6 
- [x] Convert identifiers to lowercase

## Types of changes

- [x] New feature (non-breaking change which adds functionality).
- [x] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new workflow "Deploy Jekyll site with Data Processing" to enhance site deployment with advanced data processing capabilities.
	- Added support for Omeka API integration, enabling automated data retrieval and processing from collections for site content updates.

- **Improvements**
	- Expanded workflow triggers to include additional branches for more flexible development workflows.
	- Optimized Ruby setup configuration for improved build performance.

- **Chores**
	- Cleaned up workflow configuration by removing outdated comments and unused settings.

### CODE REVIEW

**Comment by maehr** [comment]
@koilebeit Can you please take a look at the actions with https://github.com/nektos/act. My docker is on the frizz at the moment.

**Review by koilebeit — COMMENTED** [review]
When I try it with act I get following Error-Message:
`[Deploy Jekyll site with Data Processing/data-processing] ⭐ Run Main Process Data
[Deploy Jekyll site with Data Processing/data-processing]   🐳  docker exec cmd=[python /var/run/act/workflow/3.py] user= workdir=
| Traceback (most recent call last):
|   File "/var/run/act/workflow/3.py", line 72, in <module>
|     item_set = get_items_from_collection(ITEM_SET_ID)
|                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/var/run/act/workflow/3.py", line 18, in get_items_from_collection
|     response = requests.get(url, params=params)
|                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/requests/api.py", line 73, in get
|     return request("get", url, params=params, **kwargs)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/requests/api.py", line 59, in request
|     return session.request(method=method, url=url, **kwargs)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/requests/sessions.py", line 575, in request
|     prep = self.prepare_request(req)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/requests/sessions.py", line 486, in prepare_request
|     p.prepare(
|   File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/requests/models.py", line 368, in prepare
|     self.prepare_url(url, params)
|   File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url
|     raise MissingSchema(
| requests.exceptions.MissingSchema: Invalid URL 'items': No scheme supplied. Perhaps you meant https://items?
[Deploy Jekyll site with Data Processing/data-processing]   ❌  Failure - Main Process Data
[Deploy Jekyll site with Data Processing/data-processing] exitcode '1': failure
[Deploy Jekyll site with Data Processing/data-processing] 🏁  Job failed
Error: Job 'data-processing' failed`

**Comment by koilebeit** [comment]
Apart from the github action, the objectid must be lowercase (see [https://collectionbuilder.github.io/cb-docs/docs/metadata/csv_metadata/#objectid](https://collectionbuilder.github.io/cb-docs/docs/metadata/csv_metadata/#objectid)).
The object_location field is also missing, otherwise the images and data cannot be downloaded ([https://collectionbuilder.github.io/cb-docs/docs/metadata/csv_metadata/#object_location](https://collectionbuilder.github.io/cb-docs/docs/metadata/csv_metadata/#object_location))

**Comment by maehr** [comment]
> Apart from the github action, the objectid must be lowercase (see https://collectionbuilder.github.io/cb-docs/docs/metadata/csv_metadata/#objectid). The object_location field is also missing, otherwise the images and data cannot be downloaded (https://collectionbuilder.github.io/cb-docs/docs/metadata/csv_metadata/#object_location)

I get it to work with uppercase objectid (perhaps the sanitization of cb does the trick). Leaving out object_location is by design (or choice). As long as we cannot access these files directly from Omeka we cannot integrate the links.

**Comment by maehr** [comment]
> When I try it with act I get following Error-Message: `[Deploy Jekyll site with Data Processing/data-processing] ⭐ Run Main Process Data [Deploy Jekyll site with Data Processing/data-processing] 🐳 docker exec cmd=[python /var/run/act/workflow/3.py] user= workdir= | Traceback (most recent call last): | File "/var/run/act/workflow/3.py", line 72, in <module> | item_set = get_items_from_collection(ITEM_SET_ID) | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | File "/var/run/act/workflow/3.py", line 18, in get_items_from_collection | response = requests.get(url, params=params) | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/requests/api.py", line 73, in get | return request("get", url, params=params, **kwargs) | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/requests/api.py", line 59, in request | return session.request(method=method, url=url, **kwargs) | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/requests/sessions.py", line 575, in request | prep = self.prepare_request(req) | ^^^^^^^^^^^^^^^^^^^^^^^^^ | File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/requests/sessions.py", line 486, in prepare_request | p.prepare( | File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/requests/models.py", line 368, in prepare | self.prepare_url(url, params) | File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/requests/models.py", line 439, in prepare_url | raise MissingSchema( | requests.exceptions.MissingSchema: Invalid URL 'items': No scheme supplied. Perhaps you meant https://items? [Deploy Jekyll site with Data Processing/data-processing] ❌ Failure - Main Process Data [Deploy Jekyll site with Data Processing/data-processing] exitcode '1': failure [Deploy Jekyll site with Data Processing/data-processing] 🏁 Job failed Error: Job 'data-processing' failed`
> 
> edit: probably I do not have set the OS environment variables..

I added the secrets also to my fork and it seems to work https://github.com/maehr/collectionbuilder-csv/actions/runs/8173244290

**Comment by maehr** [comment]
@koilebeit the script turns all multiple/compound_items into compound_items https://github.com/maehr/collectionbuilder-csv/actions/runs/8207996344
haven't had the time to fix that.

**Comment by maehr** [comment]
@koilebeit I added multiples as well. Now the only caveat is that PDF files are not shown nor downloadable. See the build files https://github.com/maehr/collectionbuilder-csv/actions/runs/8208244993

**Comment by koilebeit** [comment]
> @koilebeit I added multiples as well. Now the only caveat is that PDF files are not shown nor downloadable. See the build files https://github.com/maehr/collectionbuilder-csv/actions/runs/8208244993

The PDF files cannot be downloaded because the column _object_location_ is empty. And they are not shown because _image_small_ and _image_thumb_ are empty (see [CB display_template](https://collectionbuilder.github.io/cb-docs/docs/metadata/csv_metadata/#display_template))

Then I noticed that the _display_template_ is still filled out incorrectly. As I understand it from the documentation [CB Compound Objects](https://collectionbuilder.github.io/cb-docs/docs/metadata/compound-objects/) the parent object gets the _display_template_ "compound_object", the sub-objects each get their format (e.g. "pdf" or "image") like this:

| objectid  | parentid | display_template |
| ------------- | ------------- |------------- |
| abb001  |  | compound_object |
| abb001_a  | abb001  | pdf |
| abb001_b  | abb001  | pdf |

**Comment by maehr** [comment]
> > @koilebeit I added multiples as well. Now the only caveat is that PDF files are not shown nor downloadable. See the build files https://github.com/maehr/collectionbuilder-csv/actions/runs/8208244993
> 
> The PDF files cannot be downloaded because the column _object_location_ is empty. And they are not shown because _image_small_ and _image_thumb_ are empty (see [CB display_template](https://collectionbuilder.github.io/cb-docs/docs/metadata/csv_metadata/#display_template))
> 
> Then I noticed that the _display_template_ is still filled out incorrectly. As I understand it from the documentation [CB Compound Objects](https://collectionbuilder.github.io/cb-docs/docs/metadata/compound-objects/) the parent object gets the _display_template_ "compound_object", the sub-objects each get their format (e.g. "pdf" or "image") like this:
> 
> objectid	parentid	display_template
> abb001		compound_object
> abb001_a	abb001	pdf
> abb001_b	abb001	pdf

I'll check again and fix it. I guess we can add the object_location by checking for the media to be private or not first.

**Review by koilebeit — APPROVED** [review]

**Pull request merged**
