### PR TITLE
Placeholder

### LINKED ISSUE #182: No Indicator in Metadata for Placeholder vs. Actual Image
### Current Behavior

In the current implementation, there is no indication in the metadata to specify whether the displayed image is the actual image of the object or a placeholder due to licensing restrictions.

**Expected Behavior**:
There should be a clear indicator or flag in the metadata (e.g., a `placeholder` field or a `license_restricted` tag) that specifies when a placeholder image is displayed instead of the actual image.

**Actual Behavior**:
Users cannot tell from the metadata alone whether they are viewing an actual image of the object or a placeholder due to licensing constraints.

**Proposed Solution**:
1. Add a field to the metadata.
2. Technical solution in the front end.

**Impact**:
This feature would enhance transparency for users and clarify the representation of the object, especially for digital collections with licensing constraints. 

### Steps To Reproduce

1. Access any item where a placeholder is used instead of the actual image.
2. Check the metadata for any indication that differentiates a placeholder from an actual image.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by maehr**
# Pull request

- Fix #182 
- [x] `assets/img/placeholder.svg` by @mtwente

## Types of changes

- [x] New feature (non-breaking change which adds functionality).
- [x] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Summary by CodeRabbit

- **New Features**
	- Enhanced metadata export functionality with additional fields: `object_location` and `image_alt_text` in the theme configuration.
	- Improved media data processing by implementing a placeholder image for specific media sources.

- **Bug Fixes**
	- Adjusted logic for downloading thumbnails based on media source to improve data processing.

- **Documentation**
	- Updated comments and structure in the theme configuration for clarity on metadata export options.

### CODE REVIEW

**Review by koilebeit — APPROVED** [review]

**Comment by mtwente** [comment]
@maehr Do you still want the placeholder to be multilingual like it is now? Alternatively, maybe we could add the license info text as a simple text string to be displayed in the item metadata when there is no image available.

**Comment by maehr** [comment]
> @maehr Do you still want the placeholder to be multilingual like it is now? Alternatively, maybe we could add the license info text as a simple text string to be displayed in the item metadata when there is no image available.

German only is fine. It needs to be as generic as possible and tell the user to check metadata for more information. Ok with you?

**Comment by maehr** [comment]
@koilebeit and @mtwente at the moment the downloadable csv and json contain the placeholder as well. We should remove that, right?

**Comment by mtwente** [comment]
What about this for an icon? (I have to update the font, it turned out a bit wobbly.)

Bildschirmfoto 2024-11-19 um 17 36 50

**Comment by maehr** [comment]
> What about this for an icon? (I have to update the font, it turned out a bit wobbly.)
> 
> Bildschirmfoto 2024-11-19 um 17 36 50

Looks fine to me! Thanks again for your work. You add it to the pull request.

**Pull request merged**
