### PR TITLE
ci: add jekyll build to ci

### PR DESCRIPTION
**Pull request by maehr**
# Pull request

## Types of changes

- [ ] New feature (non-breaking change which adds functionality).
- [x] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new Continuous Integration job for Jekyll to enhance the build process.
  
- **Chores**
	- Optimized dependency management with bundler caching in the Jekyll job.

### CODE REVIEW

**Review by koilebeit — COMMENTED** [review]
I can't test it locally:
[Continuous Integration/prettier]   ❗  ::error::Input required and not supplied: token

**Comment by maehr** [comment]
> I can't test it locally: [Continuous Integration/prettier] ❗ ::error::Input required and not supplied: token

Which token?

**Comment by koilebeit** [comment]
> > I can't test it locally: [Continuous Integration/prettier] ❗ ::error::Input required and not supplied: token
> 
> Which token?

I have no idea. I have adapted the omeka tokens locally - they work

**Comment by maehr** [comment]
@koilebeit better?

**Review by koilebeit — APPROVED** [review]

**Pull request merged**
