### PR TITLE
Custom `collection-banner.html`

### LINKED ISSUE #66: Custom collection-banner
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

I want a custom `collection-banner.html` with logo and social links.

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

_No response_

### PR DESCRIPTION
**Pull request by maehr**
# Pull request

## Proposed changes

- Fix #66 

## Types of changes

- [x] New feature (non-breaking change which adds functionality).
- [ ] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Summary by CodeRabbit

- **New Features**
	- Updated the header section with a dark-themed navigation bar, showcasing the organization's logo and social media icons for Twitter and Instagram.
	- Introduced a navigation bar component with collapsible menu and dropdown functionality for navigation items, along with a search feature.
	- Added a footer section with navigation links, organization logo display, credits, and last updated information.
	- Changed the favicon link to use the organization logo for the website.
	- Updated included files for the header, navigation bar, and footer sections.

### CODE REVIEW

**Comment by maehr** [comment]
@mtwente can you check the design?

**Comment by mtwente** [comment]
> @mtwente can you check the design?

Let me just try with little less height for the logo. It creates a lot of empty black space in the nav bar.

> Nice! Are the social media icons actually that big on purpose (also on the portal)?

On stadtgeschichtebasel.ch: yes, but here I am not so sure. I think it's weird that there are prominent links to social media accounts but not to the portal itself. For that, we obviously could not use the same logo twice.

**Comment by maehr** [comment]
The sizing comes from bootstrap directly and adheres to wcag requirements for button sizes. 

I think we should implement the nav bar in the same way as in the portal, having the hamburger left to the logo on mobile

Screenshot_20240307-115858
Screenshot_20240307-115943

What do you guys think? @koilebeit @mtwente

**Comment by maehr** [comment]
> > @mtwente can you check the design?
> 
> Let me just try with little less height for the logo. It creates a lot of empty black space in the nav bar.
> 
> > Nice! Are the social media icons actually that big on purpose (also on the portal)?
> 
> On stadtgeschichtebasel.ch: yes, but here I am not so sure. I think it's weird that there are prominent links to social media accounts but not to the portal itself. For that, we obviously could not use the same logo twice.

This i a very good point. We could have some kind of back to portal button instead of the social icons.

**Pull request merged**
