### PR TITLE
Format all files

### PR DESCRIPTION
**Pull request by koilebeit**
# Pull request

## Proposed changes

Format all files to comply with prettier

Have fun with the review ;)

## Types of changes

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Enhancement (non-breaking change which enhances functionality)
- [x] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by maehr — CHANGES_REQUESTED** [review]
Hi @koilebeit Thanks a bunch. Can you change the prettier settings for markdown to default to `*italic*` instead of `_italic_`? Apart from that I like it 🥰

**Comment by koilebeit** [comment]
> Hi @koilebeit Thanks a bunch. Can you change the prettier settings for markdown to default to `*italic*` instead of `_italic_`? Apart from that I like it 🥰

Unfortunately Prettier does not provide a built-in option to switch between asterisks and underscores for italic text. (see [https://stackoverflow.com/questions/64052818/prettier-keeps-replacing-asterisk-characters-with-underscores](https://stackoverflow.com/questions/64052818/prettier-keeps-replacing-asterisk-characters-with-underscores) or [https://github.com/prettier/prettier/issues/7165](https://github.com/prettier/prettier/issues/7165))
We would probably have to use a different tool for this.

**Comment by maehr** [comment]
> > Hi @koilebeit Thanks a bunch. Can you change the prettier settings for markdown to default to `*italic*` instead of `_italic_`? Apart from that I like it 🥰
> 
> Unfortunately Prettier does not provide a built-in option to switch between asterisks and underscores for italic text. (see https://stackoverflow.com/questions/64052818/prettier-keeps-replacing-asterisk-characters-with-underscores or [prettier/prettier#7165](https://github.com/prettier/prettier/issues/7165)) We would probably have to use a different tool for this.
> 
> But as far as I know, an underscore is also standard markdown for italic text?

Yes, underline is also accepted by https://daringfireball.net/projects/markdown/syntax but IMHO it looks shitty. But in the end personal opinions shouldn't matter. Let's go with the default.

**Review by maehr — APPROVED** [review]

**Comment by maehr** [comment]
Hi @koilebeit when I try to run the formatter via `npx prettier` or via `pnpm run format` after adding a package.json and prettierignore and prettierrc I run into error
```bash
Checking formatting...
_includes/collection-banner-sgb.html
[error] _includes/collection-banner-sgb.html: LiquidHTMLParsingError: Attempting to close HtmlElement 'a' before HtmlElement 'svg' was closed
[error]   80 |           </a>
[error]   81 |           <a href="https://www.instagram.com/sta.ge.ba/" target="_blank" class="social-icons ms-2" aria-label="Instagram" rel="noopener noreferrer">
[error] > 82 |              <svg
[error]      |              ^^^^
[error] > 83 |                 xmlns="http://www.w3.org/2000/svg"
[error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] > 84 |                 height="2em"
[error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] > 85 |                 viewBox="0 0 448 512"
[error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] > 86 |                 fill="white"
[error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] > 87 |                 >
[error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] > 88 |              <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
[error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] > 89 |              <path
[error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] > 90 |                 d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"
[error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] > 91 |                 />
[error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] > 92 |           </a>
[error]      | ^^^^^^^^^^^^^^^
[error]   93 |        </div>
[error]   94 |     </div>
[error]   95 |  </header>
_layouts/browse.html
[error] _layouts/browse.html: LiquidHTMLParsingError: Attempting to end parsing before HtmlElement 'div' was closed
[error]   45 | </div>
[error]   46 |
[error] > 47 | <div class="row" id="browseItems"></div>
[error]      |                                         ^
[error]   48 |
404.html
[error] 404.html: LiquidHTMLParsingError: Line 12, col 3: expected "svg", "style", or "script"
[error]   10 | <pre><code>
[error]   11 |  ____________
[error] > 12 | < Sorry, 404 >
[error]      |   ^
[error]   13 |  ------------
[error]   14 |         \   ^__^
[error]   15 |          \  (oo)\_______
All matched files use Prettier code style!
 ELIFECYCLE  Command failed with exit code 2.
```

```package.json
{
  "scripts": {
    "check": "prettier --check '**/*.{js,css,md,html}'",
    "format": "prettier --write ."
  },
  "dependencies": {
    "prettier": "^3.3.3",
    "@shopify/prettier-plugin-liquid": "^1.5.0"
  }
}
```

**Comment by koilebeit** [comment]
> Hi @koilebeit when I try to run the formatter via `npx prettier` or via `pnpm run format` after adding a package.json and prettierignore and prettierrc I run into error
> 
> ```shell
> Checking formatting...
> _includes/collection-banner-sgb.html
> [error] _includes/collection-banner-sgb.html: LiquidHTMLParsingError: Attempting to close HtmlElement 'a' before HtmlElement 'svg' was closed
> [error]   80 |           </a>
> [error]   81 |           <a href="https://www.instagram.com/sta.ge.ba/" target="_blank" class="social-icons ms-2" aria-label="Instagram" rel="noopener noreferrer">
> [error] > 82 |              <svg
> [error]      |              ^^^^
> [error] > 83 |                 xmlns="http://www.w3.org/2000/svg"
> [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [error] > 84 |                 height="2em"
> [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [error] > 85 |                 viewBox="0 0 448 512"
> [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [error] > 86 |                 fill="white"
> [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [error] > 87 |                 >
> [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [error] > 88 |              
> [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [error] > 89 |              <path
> [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [error] > 90 |                 d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"
> [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [error] > 91 |                 />
> [error]      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [error] > 92 |           </a>
> [error]      | ^^^^^^^^^^^^^^^
> [error]   93 |        </div>
> [error]   94 |     </div>
> [error]   95 |  </header>
> _layouts/browse.html
> [error] _layouts/browse.html: LiquidHTMLParsingError: Attempting to end parsing before HtmlElement 'div' was closed
> [error]   45 | </div>
> [error]   46 |
> [error] > 47 | <div class="row" id="browseItems"></div>
> [error]      |                                         ^
> [error]   48 |
> 404.html
> [error] 404.html: LiquidHTMLParsingError: Line 12, col 3: expected "svg", "style", or "script"
> [error]   10 | <pre><code>
> [error]   11 |  ____________
> [error] > 12 | < Sorry, 404 >
> [error]      |   ^
> [error]   13 |  ------------
> [error]   14 |         \   ^__^
> [error]   15 |          \  (oo)\_______
> All matched files use Prettier code style!
>  ELIFECYCLE  Command failed with exit code 2.
> ```
> 
> ```json
> {
>   "scripts": {
>     "check": "prettier --check '**/*.{js,css,md,html}'",
>     "format": "prettier --write ."
>   },
>   "dependencies": {
>     "prettier": "^3.3.3",
>     "@shopify/prettier-plugin-liquid": "^1.5.0"
>   }
> }
> ```

Thanks for the review. Now it should be fixed. I can add the scripts in #149

**Review by maehr — APPROVED** [review]
Prettier runs smoothly and it builds as well. Thanks a bunch

**Pull request merged**
