### PR TITLE
Tabled item

### LINKED ISSUE #142: New item layout: Table
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

A new item view for csv-tables. So far, a csv media object looks like this:
image

A table view could look like this:
image

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

_No response_

### PR DESCRIPTION
**Pull request by koilebeit**
# Pull request

## Proposed changes

closes #142 
## Types of changes

- [x] New feature (non-breaking change which adds functionality).
- [ ] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Summary by CodeRabbit

- **New Features**
  - Introduced table display functionality for CSV data, including sorting and search features.
  
- **Improvements**
  - Enhanced download buttons to distinguish between Vimeo and YouTube videos, providing specific actions for each.
  - Updated styles for better visual consistency and improved datatable presentation.

### CODE REVIEW

**Comment by koilebeit** [comment]
> Thank you for this PR. It is a great addition! The only caveat is the styling, i.e. the colors. @mtwente might be able to tweak that.

Yes, you are right. We could take the color out completely. But somehow I would like it to stand out a bit from the metadata on the right and differentiate it

**Comment by mtwente** [comment]
> Thank you for this PR. It is a great addition! The only caveat is the styling, i.e. the colors. @mtwente might be able to tweak that.

How about a thin yellow border? This would be a visual correspondence to the yellow frame on https://forschung.stadtgeschichtebasel.ch/subjects.html

table_border_hover

A yellow border around the table element. The row the user is hovering on is highlighted in yellow, too.

Alternatively: Have the border around the actual csv content only (inner table border):

table_inner_border

(This way, the bottom and right borders are only displayed if you scroll all the way)

**Comment by koilebeit** [comment]
> > Thank you for this PR. It is a great addition! The only caveat is the styling, i.e. the colors. @mtwente might be able to tweak that.
> 
> How about a thin yellow border? This would be an approximate visual correspondence to the yellow frame on https://forschung.stadtgeschichtebasel.ch/subjects.html
> table_border_hover
> 
> A yellow border around the table element. The row the user is hovering on is highlighted in yellow, too.
> 
> Alternatively: Have the border around the actual csv content only (inner table border):
> table_inner_border
> 
> (This way, the bottom and right borders are only displayed if you scroll all the way)

That's a good idea. I would prefer the first variant. And hovering is not really necessary(?)

**Comment by maehr** [comment]
> > > Thank you for this PR. It is a great addition! The only caveat is the styling, i.e. the colors. @mtwente might be able to tweak that.
> > 
> > 
> > How about a thin yellow border? This would be an approximate visual correspondence to the yellow frame on https://forschung.stadtgeschichtebasel.ch/subjects.html
> > table_border_hover
> > A yellow border around the table element. The row the user is hovering on is highlighted in yellow, too.
> > Alternatively: Have the border around the actual csv content only (inner table border):
> > table_inner_border
> > (This way, the bottom and right borders are only displayed if you scroll all the way)
> 
> That's a good idea. I would prefer the first variant. And hovering is not really necessary(?)

I also like the first variant!

**Comment by mtwente** [comment]
An updated version with the top row also in yellow. We could make the top row with column names sticky to improve readability when scrolling down (also on the main metadata table) as it is [here](https://datatables.net/extensions/responsive/examples/column-control/fixedHeader.html).

yellow_top_row

**Comment by koilebeit** [comment]
> An updated version with the top row also in yellow. We could make the top row with column names sticky to improve readability when scrolling down (also on the main metadata table) as it is [here](https://datatables.net/extensions/responsive/examples/column-control/fixedHeader.html).
> yellow_top_row
> I also removed the hovering colour again, and made the filter field sticky so it is still visible when scrolling horizontally.

Great! Waiting for your commit

**Comment by koilebeit** [comment]
> This should do it for now:
> screenshot
> 
> But there still seems something broken at the very right end of the table (scroll e.g. to the last column of entry with ID 12093).

I found the problem: the csv is not parsed correctly yet, because so far it strictly splits at every comma, even if it occurs within quotation marks in a column

**Comment by maehr** [comment]
@koilebeit Thanks for this quick fix with papaparse. This looks like a sustainable solution. Please fix the merge conflict of the scss file from main and we are good to go 🎉

**Review by maehr — APPROVED** [review]

**Pull request merged**
